import { Category } from '@/types/budget';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'rent',
    name: 'Rent',
    color: '#FF6B6B',
    icon: 'home',
    order: 0,
    type: 'expense',
    isActive: true,
  },
  {
    id: 'utilities',
    name: 'Utilities',
    color: '#4ECDC4',
    icon: 'zap',
    order: 1,
    type: 'expense',
    isActive: true,
  },
  {
    id: 'groceries',
    name: 'Groceries',
    color: '#95E1D3',
    icon: 'shopping-cart',
    order: 2,
    type: 'expense',
    isActive: true,
  },
  {
    id: 'gas',
    name: 'Gas',
    color: '#F38181',
    icon: 'fuel',
    order: 3,
    type: 'expense',
    isActive: true,
  },
  {
    id: 'dining',
    name: 'Eating Out',
    color: '#AA96DA',
    icon: 'utensils',
    order: 4,
    type: 'expense',
    isActive: true,
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    color: '#FCBAD3',
    icon: 'tv',
    order: 5,
    type: 'expense',
    isActive: true,
  },
  {
    id: 'savings',
    name: 'Savings',
    color: '#A8D8EA',
    icon: 'piggy-bank',
    order: 6,
    type: 'expense',
    isActive: true,
  },
  {
    id: 'misc',
    name: 'Miscellaneous',
    color: '#FFD93D',
    icon: 'more-horizontal',
    order: 7,
    type: 'expense',
    isActive: true,
  },
];
